In [126]:
import requests
import pandas as pd 
from bs4 import BeautifulSoup

In [127]:
years = list(range(2022, 2023))
conference = ["E", "W"]
for year in years:
    print(year)

2022

In [128]:
def getAbbr(teamName):
    if teamName == "Miami Heat":
        return "MIA"
    elif teamName == "Boston Celtics":
        return "BOS"
    elif teamName == "Milwaukee Bucks":
        return "MIL"
    elif teamName == "Philadelphia 76ers":
        return "PHI"
    elif teamName == "Toronto Raptors":    
        return "TOR"
    elif teamName == "Chicago Bulls":    
        return "CHI"
    elif teamName == "Brooklyn Nets":        
        return "BRK"
    elif teamName == "Cleveland Cavaliers":   
        return "CLE"
    elif teamName == "Atlanta Hawks":
        return "ATL"
    elif teamName == "Charlotte Hornets":
        return "CHO"
    elif teamName == "New York Knicks":
        return "NYK"
    elif teamName == "Washington Wizards":
        return "WAS"
    elif teamName == "Indiana Pacers":
        return "IND"
    elif teamName == "Detroit Pistons":
        return "DET"
    elif teamName == "Orlando Magic":
        return "ORL"
    elif teamName == "Phoenix Suns":
        return "PHO"
    elif teamName == "Memphis Grizzlies":
        return "MEM"
    elif teamName == "Golden State Warriors":
        return "GSW"
    elif teamName == "Dallas Mavericks":
        return "DAL"
    elif teamName == "Utah Jazz":
        return "UTA"
    elif teamName == "Denver Nuggets":
        return "DEN"
    elif teamName == "Minnesota Timberwolves":
        return "MIN"
    elif teamName == "Los Angeles Clippers":
        return "LAC"
    elif teamName == "New Orleans Pelicans":
        return "NOP"
    elif teamName == "San Antonio Spurs":
        return "SAS"
    elif teamName == "Los Angeles Lakers":
        return "LAL"
    elif teamName == "Sacramento Kings":
        return "SAC"
    elif teamName == "Portland Trail Blazers":
        return "POR"
    elif teamName == "Oklahoma City Thunder":
        return "OKC"
    elif teamName == "Houston Rockets":
        return "HOU"

In [129]:
url_start = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [130]:
for year in years:
    url = url_start.format(year)
    data = requests.get(url)

    with open("standings/{}_standings.html".format(year), "w+", encoding="utf-8") as f:
        f.write(data.text)

In [131]:
standings = {}

for c in conference:
    idName = "confs_standings_" + c
    for year in years:
        with open("standings/{}_standings.html".format(year), encoding="utf-8") as f:
            page = f.read()

            soup = BeautifulSoup(page, "html.parser")
            totals = soup.find(id=idName)
            standings[str(year) + "_" + c] = pd.read_html(str(totals))[0]

In [132]:

data = []

for x in standings:
    standingsHeader = standings[x].columns[0]
    for index, row in standings[x].iterrows():
        data.append([getAbbr(row[standingsHeader].replace("*", "")), row["W/L%"]])

standings = pd.DataFrame(data, columns=['team', 'winPC'])

display(standings)

   team  winPC
0   MIA  0.646
1   BOS  0.622
2   MIL  0.622
3   PHI  0.622
4   TOR  0.585
5   CHI  0.561
6   BRK  0.537
7   CLE  0.537
8   ATL  0.524
9   CHO  0.524
10  NYK  0.451
11  WAS  0.427
12  IND  0.305
13  DET  0.280
14  ORL  0.268
15  PHO  0.780
16  MEM  0.683
17  GSW  0.646
18  DAL  0.634
19  UTA  0.598
20  DEN  0.585
21  MIN  0.561
22  LAC  0.512
23  NOP  0.439
24  SAS  0.415
25  LAL  0.402
26  SAC  0.366
27  POR  0.329
28  OKC  0.293
29  HOU  0.244